
variable "centos_password" {
  type    = string
  default = "ubuntu"
}

variable "version" {
  type    = string
  default = "2009"
}

source "qemu" "autogenerated_1" {
  boot_command     = ["<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"]
  boot_wait        = "2s"
  cpus             = 1
  headless         = true
  http_directory   = "http"
  iso_checksum     = "07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a"
  iso_target_path  = "iso"
  iso_urls         = ["iso/CentOS-7-x86_64-Minimal-${var.version}.iso", "http://mirror.de.leaseweb.net/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-${var.version}.iso"]
  memory           = "512"
  output_directory = "output-centos"
  qemuargs         = [["-cpu", "host"]]
  shutdown_command = "echo '${var.centos_password}' | sudo -S /sbin/halt -h -p"
  ssh_password     = "${var.centos_password}"
  ssh_timeout      = "20m"
  ssh_username     = "centos"
  vm_name          = "centos-packer.qcow2"
}

build {
  sources = ["source.qemu.autogenerated_1"]

}
